import XCTest
@testable import SentryKit

/// Exercises the real Keychain (see `MCPRemoteAccessKey`'s doc comment for
/// why there's no fake/injectable store) against a unique `account` per test
/// so runs never collide with each other or with a real "default" key a
/// developer might have generated by using the app.
final class MCPRemoteAccessKeyTests: XCTestCase {

    private var accountNames: [String] = []

    override func tearDown() {
        for account in accountNames {
            MCPRemoteAccessKey.clear(account: account)
        }
        accountNames.removeAll()
        super.tearDown()
    }

    private func uniqueAccount(_ name: String) -> String {
        let account = "test.\(name).\(UUID().uuidString)"
        accountNames.append(account)
        return account
    }

    func testCurrentIsNilBeforeAnyKeyIsGenerated() {
        let account = uniqueAccount("neverGenerated")
        XCTAssertNil(MCPRemoteAccessKey.current(account: account))
    }

    func testRegenerateStoresAKeyThatCurrentThenReturns() {
        let account = uniqueAccount("regenerateThenCurrent")
        let key = MCPRemoteAccessKey.regenerate(account: account)

        XCTAssertFalse(key.isEmpty)
        XCTAssertEqual(MCPRemoteAccessKey.current(account: account), key)
    }

    func testRegenerateProducesADifferentKeyEachTime() {
        let account = uniqueAccount("regenerateTwice")
        let first = MCPRemoteAccessKey.regenerate(account: account)
        let second = MCPRemoteAccessKey.regenerate(account: account)

        XCTAssertNotEqual(first, second)
        XCTAssertEqual(MCPRemoteAccessKey.current(account: account), second)
    }

    func testClearRemovesTheStoredKey() {
        let account = uniqueAccount("clear")
        MCPRemoteAccessKey.regenerate(account: account)
        XCTAssertNotNil(MCPRemoteAccessKey.current(account: account))

        MCPRemoteAccessKey.clear(account: account)
        XCTAssertNil(MCPRemoteAccessKey.current(account: account))
    }

    func testClearOnAnAlreadyClearAccountDoesNotThrowOrCrash() {
        let account = uniqueAccount("clearTwice")
        MCPRemoteAccessKey.clear(account: account)
        MCPRemoteAccessKey.clear(account: account)
        XCTAssertNil(MCPRemoteAccessKey.current(account: account))
    }

    func testGeneratedKeyIsHexEncodedThirtyTwoBytes() {
        let account = uniqueAccount("hexShape")
        let key = MCPRemoteAccessKey.regenerate(account: account)

        XCTAssertEqual(key.count, 64, "32 bytes hex-encoded should be 64 characters")
        XCTAssertTrue(key.allSatisfy(\.isHexDigit))
    }
}
