import Foundation

// MARK: - The update channel's configuration, as a value that can be wrong

/// Whether this build is actually able to check for and install an update,
/// and — when it isn't — the specific reason, in words that are safe to put
/// on screen verbatim.
///
/// **Why an enum with no plain `.ready` shortcut for "probably fine."**
/// Sentry ships outside the Mac App Store (Developer ID + notarization), so
/// Sparkle is the *only* update channel this app will ever have. That makes
/// the updater's configuration a piece of load-bearing state that can be
/// silently, invisibly broken: an appcast URL that 404s, an EdDSA public key
/// that doesn't match the private key the release was signed with, or — the
/// case this build is actually in — a placeholder public key that was never
/// replaced. In every one of those situations Sparkle's own behaviour is to
/// fail quietly or with an error the user reads as "the server is down."
///
/// This codebase has a hard rule against controls that silently do nothing
/// (see `SyncPane`'s doc comment for the canonical writeup, and
/// `AIAccessPane`'s helper-status section for another application of it).
/// A "Check for
/// Updates…" button that spins and then says "You're up to date!" because
/// the signature check rejected every item in the feed is exactly that bug,
/// in its most dangerous form — the user believes they are current when they
/// are not. So the configuration is inspected up front, before any updater
/// object exists, and the answer is a value the UI is required to switch
/// over.
///
/// **This is deliberately not `Bool`-shaped.** `canCheckForUpdates` exists
/// for the one place that genuinely needs a boolean (enabling a button), but
/// every reason case carries its own `headline`/`explanation` so the pane
/// can say *which* thing is wrong. "Updates are unavailable" with no reason
/// is the same lie in a quieter voice.
///
/// **Failure cases are ordered by what a person can do about them.** A
/// placeholder public key is a release-engineering to-do the developer owns
/// (`generate_keys`, then back the private key up — see
/// `docs/sparkle-release-signing.md`); a malformed feed URL is a build
/// misconfiguration; a `startFailed` is Sparkle itself refusing at runtime.
/// They are separate cases rather than one `.misconfigured(String)` so that
/// adding a new blocker breaks every exhaustive switch, including the pane's
/// on-screen copy — the same compile-time-honesty trick
/// `MCPBridgeRegistration` uses, where every state a caller might mistake
/// for "working" has to be spelled out and handled.
public enum UpdaterAvailability: Equatable, Sendable {

    /// Everything a signed update needs is present and well-formed: an
    /// `https` feed URL and a 32-byte Ed25519 public key. Note carefully
    /// what this does **not** promise — that the key is the *right* key, or
    /// that anything is actually published at that URL. Neither is knowable
    /// without a network round trip, and Sparkle checks both itself at
    /// update time. This case means "the app is correctly configured to
    /// try," nothing more.
    case ready(feedURL: URL)

    /// No `SUFeedURL` in the bundle at all. Sparkle would have nowhere to
    /// look; the app is effectively update-less.
    case feedURLMissing

    /// `SUFeedURL` isn't parseable as a URL with a host.
    case feedURLMalformed(String)

    /// `SUFeedURL` parses but isn't `https`. Refused rather than tolerated:
    /// the appcast is the document that tells the app which binary to
    /// download, and serving it over plaintext hands a network attacker the
    /// ability to point the updater anywhere. The EdDSA signature still
    /// protects the *payload*, but a downgrade to a genuinely-signed older
    /// build, or an endless "no updates available," both survive a
    /// signature check untouched.
    case feedURLInsecure(String)

    /// No `SUPublicEDKey` in the bundle. Sparkle 2 refuses to install
    /// anything without one, which is correct — but it refuses *late*, after
    /// a download, in a way that reads as a server problem.
    case publicKeyMissing

    /// `SUPublicEDKey` is still the placeholder this repo ships. The key
    /// pair is deliberately **not** generated by tooling or by an assistant:
    /// the private half is a secret the developer must own and personally
    /// back up, and losing it permanently orphans every installed copy —
    /// there is no recovery path, no revocation, no re-key. See
    /// `docs/sparkle-release-signing.md`.
    case publicKeyPlaceholder

    /// `SUPublicEDKey` is present but isn't base64 of exactly 32 bytes, so
    /// it cannot be an Ed25519 public key. Usually a truncated copy-paste.
    case publicKeyMalformed(String)

    /// Sparkle's own `startUpdater()` threw. Only ever produced at runtime
    /// by the updater wrapper — never by inspecting a bundle — but it lives
    /// in this enum so that every consumer has exactly one vocabulary for
    /// "the updater is not going to work, and here's why."
    case startFailed(String)

    /// The one place a boolean is the right shape: whether a "Check for
    /// Updates…" control should be operable at all. Everything else about
    /// presenting these states should switch over the case, not branch on
    /// this.
    public var canCheckForUpdates: Bool {
        if case .ready = self { return true }
        return false
    }

    /// One short sentence, suitable as the bold line of a status row.
    /// Present tense, factual, never aspirational.
    public var headline: String {
        switch self {
        case .ready:
            return String(localized: "Sentry can check for updates.")
        case .feedURLMissing, .feedURLMalformed, .feedURLInsecure:
            return String(localized: "Automatic updates aren't configured in this build.")
        case .publicKeyMissing, .publicKeyPlaceholder, .publicKeyMalformed:
            return String(localized: "Automatic updates are turned off in this build.")
        case .startFailed:
            return String(localized: "The updater failed to start.")
        }
    }

    /// The full explanation, written to be read by the person running the
    /// app — including when that person is the developer, who is the only
    /// one who can fix most of these.
    public var explanation: String {
        switch self {
        case .ready(let feedURL):
            return String(
                localized: "Sentry checks \(feedURL.absoluteString) and installs only updates signed with the key built into this copy. Updates are downloaded and applied by Sparkle."
            )
        case .feedURLMissing:
            return String(localized: "This build has no update feed address, so there is nowhere for Sentry to look. Update manually by downloading a newer build.")
        case .feedURLMalformed(let raw):
            return String(localized: "The update feed address in this build isn't a usable URL (“\(raw)”), so Sentry can't check for updates. Update manually by downloading a newer build.")
        case .feedURLInsecure(let raw):
            return String(localized: "The update feed address in this build isn't served over HTTPS (“\(raw)”). Sentry refuses to fetch an update list over a plaintext connection, because anything on the network could rewrite it. Update manually by downloading a newer build.")
        case .publicKeyMissing:
            return String(localized: "This build carries no update-signing key, so Sentry has no way to tell a genuine update from a tampered one — and it won't install one it can't verify. Update manually by downloading a newer build.")
        case .publicKeyPlaceholder:
            return String(localized: "This build carries a placeholder update-signing key rather than a real one, so no update could ever be verified. Rather than show a Check for Updates button that would always come back empty, Sentry says so here. Update manually by downloading a newer build.")
        case .publicKeyMalformed(let reason):
            return String(localized: "This build's update-signing key isn't valid (\(reason)), so Sentry has no way to verify an update and won't install one. Update manually by downloading a newer build.")
        case .startFailed(let reason):
            return String(localized: "Sparkle refused to start on this launch (\(reason)), so update checking is unavailable until Sentry is relaunched. Update manually by downloading a newer build.")
        }
    }
}

// MARK: - UpdateFeedConfiguration

/// Reads and validates the two `Info.plist` keys Sparkle's update channel
/// depends on — `SUFeedURL` and `SUPublicEDKey` — without importing Sparkle.
///
/// **Why this is a separate, framework-free type.** Two reasons, both
/// practical. First, it makes the "is the updater actually going to work"
/// question answerable in a unit test on any machine, with no Sparkle
/// object, no network, and no bundle: the initializer takes plain strings.
/// Second, it means the *decision* to not construct an updater at all lives
/// in code that can't accidentally construct one — `UpdateController`
/// (`Sentry/App/UpdateController.swift`) asks this type first and only
/// touches Sparkle if the answer is `.ready`.
///
/// **Where the values come from.** Both keys are written into the app's
/// `Info.plist` by `project.yml`'s `Sentry` target `info.properties` block,
/// which is the single source of truth — the checked-in
/// `Sentry/Resources/Info.plist` is regenerated by `xcodegen generate`, so
/// editing it directly does not survive. That file also carries the warning
/// worth repeating here: **`SUFeedURL` is compiled into every shipped binary
/// and cannot be changed retroactively on copies already installed.** If the
/// feed ever has to move, the only way to move an existing install is to
/// ship an update *through the old feed* that points at the new one. Pick
/// the address once.
public struct UpdateFeedConfiguration: Equatable, Sendable {

    /// The exact string this repo ships in `SUPublicEDKey` until a real key
    /// pair is generated. Deliberately not base64-of-32-bytes and
    /// deliberately shouty, so that (a) `publicKeyMalformed` can never be
    /// confused with "you forgot to replace the placeholder," and (b) a
    /// grep for it finds every place that has to change.
    public static let placeholderPublicKey = "REPLACE-WITH-YOUR-SPARKLE-ED25519-PUBLIC-KEY"

    /// Ed25519 public keys are exactly 32 bytes; Sparkle stores them
    /// base64-encoded. Anything else cannot be one.
    public static let publicKeyByteCount = 32

    public let feedURLString: String?
    public let publicKeyString: String?

    public init(feedURLString: String?, publicKeyString: String?) {
        self.feedURLString = feedURLString
        self.publicKeyString = publicKeyString
    }

    /// Reads both keys out of a bundle's `Info.plist`. Defaults to
    /// `.main` — the app itself — but takes a parameter so tests and the
    /// preview path can supply their own.
    public init(bundle: Bundle) {
        self.init(
            feedURLString: bundle.object(forInfoDictionaryKey: "SUFeedURL") as? String,
            publicKeyString: bundle.object(forInfoDictionaryKey: "SUPublicEDKey") as? String
        )
    }

    /// What this configuration means for the user, computed fresh each time
    /// (it's cheap, and caching would only create a way for it to go stale).
    ///
    /// **Check order is deliberate: key first, then feed.** Both can be
    /// wrong at once, and only one message fits on screen. The signing key
    /// is the more consequential of the two — a wrong feed URL produces an
    /// update check that visibly fails, whereas a wrong or placeholder key
    /// produces one that *silently succeeds at finding nothing*, which is
    /// the failure mode this whole type exists to prevent.
    public var availability: UpdaterAvailability {
        let trimmedKey = publicKeyString?.trimmingCharacters(in: .whitespacesAndNewlines)

        guard let key = trimmedKey, !key.isEmpty else {
            return .publicKeyMissing
        }
        if key == Self.placeholderPublicKey {
            return .publicKeyPlaceholder
        }
        guard let decoded = Data(base64Encoded: key) else {
            return .publicKeyMalformed(String(localized: "it isn't valid base64"))
        }
        guard decoded.count == Self.publicKeyByteCount else {
            return .publicKeyMalformed(
                String(localized: "it decodes to \(decoded.count) bytes, not \(Self.publicKeyByteCount)")
            )
        }

        let trimmedFeed = feedURLString?.trimmingCharacters(in: .whitespacesAndNewlines)
        guard let feed = trimmedFeed, !feed.isEmpty else {
            return .feedURLMissing
        }
        guard let url = URL(string: feed), let scheme = url.scheme, url.host?.isEmpty == false else {
            return .feedURLMalformed(feed)
        }
        guard scheme.lowercased() == "https" else {
            return .feedURLInsecure(feed)
        }

        return .ready(feedURL: url)
    }
}
